# Generated by Django 5.1.4 on 2025-01-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_alter_condition_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['surfzone', 'month']},
        ),
    ]
