# Generated by Django 5.1.4 on 2025-02-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0015_alter_continent_options_alter_country_options_and_more'),
        ('users', '0007_alter_review_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'surf_spot')},
        ),
    ]
