# Generated by Django 5.1.4 on 2025-05-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0022_alter_surfspotimage_options'),
        ('users', '0008_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'surf_spot'), ('user', 'surf_zone')},
        ),
    ]
