# Generated by Django 5.1.4 on 2025-01-04 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
                ('break_type', models.CharField(max_length=100)),
                ('left', models.BooleanField(default=False)),
                ('right', models.BooleanField(default=False)),
                ('left_and_right', models.BooleanField(default=False)),
                ('best_wind', models.CharField(max_length=100)),
                ('best_swell_direction', models.CharField(max_length=100)),
                ('best_swell_size', models.FloatField(max_length=10)),
                ('best_tide', models.CharField(max_length=100)),
                ('surf_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfzones.continent')),
            ],
        ),
        migrations.CreateModel(
            name='SurfSpotImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='surfspots/')),
                ('description', models.TextField(blank=True, null=True)),
                ('surf_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_images', to='surfzones.surfspot')),
            ],
        ),
        migrations.CreateModel(
            name='SurfZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nearest_city', models.CharField(max_length=100)),
                ('nearest_airport', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, max_length=10, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=10, null=True)),
                ('solo', models.BooleanField(default=False)),
                ('couple', models.BooleanField(default=False)),
                ('family', models.BooleanField(default=False)),
                ('safety', models.CharField(blank=True, max_length=100, null=True)),
                ('health', models.CharField(blank=True, max_length=100, null=True)),
                ('confort', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('surroundings', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lefts', models.BooleanField(default=False)),
                ('rights', models.BooleanField(default=False)),
                ('left_and_rights', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfzones.country')),
            ],
        ),
        migrations.AddField(
            model_name='surfspot',
            name='surfzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_spots', to='surfzones.surfzone'),
        ),
        migrations.CreateModel(
            name='SurfZoneImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='surfzones/')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('surfzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_images', to='surfzones.surfzone')),
            ],
        ),
    ]
