# Generated by Django 5.1.4 on 2025-01-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surfspotimage',
            old_name='surf_spot',
            new_name='surfspot',
        ),
    ]
