# Generated by Django 5.1.4 on 2025-01-11 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0007_remove_surfspot_left_remove_surfspot_left_and_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='best_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='best_tide',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='surf_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Pro', 'Pro')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('left_and_right', 'Left and Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='best_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='confort',
            field=models.CharField(blank=True, choices=[('Simple', 'Simple'), ('Comfortable', 'Comfortable'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='main_wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('left_and_right', 'Left and Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='safety',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=100),
        ),
    ]
