# Generated by Django 5.1.4 on 2025-01-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='surf_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=50),
        ),
    ]
