# Generated by Django 5.1.4 on 2025-01-09 22:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0002_alter_surfspot_surf_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='surf_hazards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
