# Generated by Django 5.1.4 on 2025-01-10 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0005_alter_surfspot_best_tide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='best_tide',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='surf_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=20), blank=True, null=True, size=None),
        ),
    ]
