# Generated by Django 5.1.4 on 2025-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0008_alter_surfspot_best_months_alter_surfspot_best_tide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left_and_right', 'Left and Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='main_wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left_and_right', 'Left and Right')], max_length=20),
        ),
    ]
