# Generated by Django 5.1.4 on 2025-01-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0009_alter_surfspot_wave_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspotimage',
            name='image',
            field=models.ImageField(upload_to='surfzones/surf_spots_images'),
        ),
        migrations.AlterField(
            model_name='surfzoneimage',
            name='image',
            field=models.ImageField(upload_to='surfzones/surf_zones_images'),
        ),
    ]
