# Generated by Django 5.1.4 on 2025-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0010_alter_surfspotimage_image_alter_surfzoneimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspotimage',
            name='image',
            field=models.ImageField(upload_to='surfspots/surf_spots_images'),
        ),
    ]
