# Generated by Django 5.1.4 on 2025-01-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0014_alter_surfspot_break_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='surfspot',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='surfzone',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='surfzoneimage',
            options={'ordering': ['surfzone']},
        ),
    ]
