# Generated by Django 5.1.4 on 2025-02-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0015_alter_continent_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left and right', 'Left and Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='main_wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left and right', 'Left and Right')], max_length=20),
        ),
    ]
