# Generated by Django 5.1.4 on 2025-02-15 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0016_alter_surfspot_wave_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='best_swell_size_meter',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
