# Generated by Django 5.1.4 on 2025-02-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0017_surfspot_best_swell_size_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surfspot',
            old_name='best_swell_size',
            new_name='best_swell_size_feet',
        ),
    ]
