# Generated by Django 5.1.4 on 2025-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0018_rename_best_swell_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfzone',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
