# Generated by Django 5.1.4 on 2025-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0019_surfzone_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfzone',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
