# Generated by Django 5.1.4 on 2025-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0020_surfzone_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left and right', 'Left and right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surfzone',
            name='main_wave_direction',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Left and right', 'Left and right')], max_length=20),
        ),
    ]
