# Generated by Django 5.1.4 on 2025-05-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfzones', '0021_alter_surfspot_wave_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfspotimage',
            options={'ordering': ['surfspot']},
        ),
    ]
