# ============================
# Base Image
# ============================
FROM python:3.12.5-alpine

# ============================
# Environment Variables
# ============================
# Prevents Python from writing pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
# Ensures output is shown in Docker logs
ENV PYTHONUNBUFFERED=1
# Set environment to development
ENV ENVIRONMENT=development
ENV DJANGO_ENV=dev
ENV DJANGO_SETTINGS_MODULE=surfquest.settings.dev
ENV PYTHONPATH=/app:/app/surfquest

# ============================
# Working Directory
# ============================
WORKDIR /app

# ============================
# Dependencies Installation
# ============================
# Install dependencies needed for building Python packages
RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    postgresql-dev \
    postgresql-client \
    bash

# Copy requirements and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# ============================
# Application Code
# ============================
COPY . /app
RUN touch /app/surfquest/settings/__init__.py
RUN touch /app/surfquest/__init__.py


# ============================
# Volume for Media Files
# ============================
VOLUME ["/app/media"]

# ============================
# Expose Port
# ============================
EXPOSE 8000

# ============================
# Command to Run Server
# ============================
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]