# Generated by Django 5.1.4 on 2025-01-04 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surfzones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=100)),
                ('water_temp', models.IntegerField()),
                ('swell_size', models.FloatField(max_length=10)),
                ('swell_consistancy', models.IntegerField()),
                ('swell_direction', models.CharField(max_length=100)),
                ('beginers', models.BooleanField(default=False)),
                ('intermediate', models.BooleanField(default=False)),
                ('advanced', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('crowds', models.CharField(max_length=100)),
                ('local_surf_quality', models.CharField(max_length=100)),
                ('global_surf_rating', models.CharField(max_length=100)),
                ('min_air_temp', models.IntegerField()),
                ('max_air_temp', models.IntegerField()),
                ('rain_quantity', models.IntegerField()),
                ('rain_days', models.IntegerField()),
                ('wind_force', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=100)),
                ('wind_consistency', models.IntegerField()),
                ('surfzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='surfzones.surfzone')),
            ],
        ),
    ]
