# Generated by Django 5.1.4 on 2025-01-11 15:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='beginner',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='intermediate',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='max_air_temp',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='min_air_temp',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='water_temp',
        ),
        migrations.AddField(
            model_name='condition',
            name='max_air_temp_c',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='max_air_temp_f',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(212)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='min_air_temp_c',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='min_air_temp_f',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-148), django.core.validators.MaxValueValidator(212)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='surf_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Pro', 'Pro')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='condition',
            name='water_temp_c',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='condition',
            name='water_temp_f',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(86)]),
        ),
        migrations.AlterField(
            model_name='condition',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=12),
        ),
        migrations.AlterField(
            model_name='condition',
            name='swell_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('N-NE', 'North-northeast'), ('NE', 'Northeast'), ('E-NE', 'East-northeast'), ('E', 'East'), ('E-SE', 'East-southeast'), ('SE', 'Southeast'), ('S-SE', 'South-southeast'), ('S', 'South'), ('S-SW', 'South-southwest'), ('SW', 'Southwest'), ('W-SW', 'West-southwest'), ('W', 'West'), ('W-NW', 'West-northwest'), ('NW', 'Northwest'), ('N-NW', 'North-northwest')], max_length=10),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('N-NE', 'North-northeast'), ('NE', 'Northeast'), ('E-NE', 'East-northeast'), ('E', 'East'), ('E-SE', 'East-southeast'), ('SE', 'Southeast'), ('S-SE', 'South-southeast'), ('S', 'South'), ('S-SW', 'South-southwest'), ('SW', 'Southwest'), ('W-SW', 'West-southwest'), ('W', 'West'), ('W-NW', 'West-northwest'), ('NW', 'Northwest'), ('N-NW', 'North-northwest')], max_length=10),
        ),
    ]
